#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

password=$YNH_APP_ARG_PASSWORD
in_port="1080"
out_port=$YNH_APP_ARG_OUT_PORT
cipher=$YNH_APP_ARG_CIPHER
ip=$(ip addr | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | egrep -v "^192\.168|^172\.1[6-9]\.|^172\.2[0-9]\.|^172\.3[0-2]\.|^10\.|^127\.|^255\.|^0\." | head -n 1 )

app=$YNH_APP_INSTANCE_NAME

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
ynh_print_info "Storing installation settings..."

ynh_app_setting_set $app password $password
ynh_app_setting_set $app cipher $cipher

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# FIND AND OPEN A PORT
#=================================================
ynh_print_info "Configuring firewall..."

# Find a free port
port=$(ynh_find_port $out_port)
# Open this port
ynh_exec_warn_less yunohost firewall allow --no-upnp Both $port
ynh_app_setting_set $app port $port

# Find a free internal port
internal_port=$(ynh_find_port $in_port)
# Open this port
ynh_app_setting_set $app internal_port $internal_port

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_print_info "Installing dependencies..."

ynh_install_app_dependencies $pkg_dependencies

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_print_info "Setting up source files..."

tmpdir="$(ynh_smart_mktemp 300)"

ynh_print_info "Extracting libsodium sorces into temp directory for installation..."
# Download, check integrity, uncompress and patch the source from libsodium.src
ynh_setup_source "${tmpdir}/${libsodium_file}" "libsodium"

ynh_print_info "Extracting shadowsocks sorces into temp directory for installation..."
# Download, check integrity, uncompress and patch the source from shadowsocks.src
ynh_setup_source "${tmpdir}/shadowsocks" "shadowsocks"

#=================================================
# SPECIFIC SETUP
#=================================================

# Install Shadowsocks

    # Install libsodium
    if [ ! -f /usr/lib/libsodium.a ]; then
       (
       cd ${tmpdir}/${libsodium_file}
       ./configure --prefix=/usr && make && make install
       )
    fi

    # Install Shadowsocks
    (
    cd ${tmpdir}/shadowsocks
    python setup.py install --record /usr/local/shadowsocks_install.log
    )
    if [ -f /usr/bin/ssserver ] || [ -f /usr/local/bin/ssserver ]; then
        cp -f "../conf/shadowsocks.json" "/etc/."
        cp -f "../conf/shadowsocks" "/etc/init.d/."
        chmod +x /etc/init.d/shadowsocks
        update-rc.d -f shadowsocks defaults
        
        #=================================================
		# MODIFY A CONFIG FILE
		#=================================================

		### `ynh_replace_string` is used to replace a string in a file.
		### (It's compatible with sed regular expressions syntax)

		ynh_replace_string "__PORT__"          "$port"          "/etc/shadowsocks.json"
		ynh_replace_string "__INTERNAL_PORT__" "$internal_port" "/etc/shadowsocks.json"
		ynh_replace_string "__PASSWORD__"      "$password"      "/etc/shadowsocks.json"
		ynh_replace_string "__CIPHER__"        "$cipher"        "/etc/shadowsocks.json"
    else
        ynh_die "Shadowsocks install failed! please open an issue here https://github.com/YunoHost-Apps/shadowsocks_ynh/issues"
fi

rm -Rf "$tmpdir"

#=================================================
# STORE THE CONFIG FILE CHECKSUM
#=================================================

# Calculate and store the config file checksum into the app settings
ynh_store_file_checksum "/etc/shadowsocks.json"

#=================================================
# ADVERTISE SERVICE IN ADMIN PANEL
#=================================================

yunohost service add $app --log "/var/log/$app.log"
# if using yunohost version 3.2 or more in the 'manifest.json', a description can be added
yunohost service add $app --description "$app daemon for Shadowsocks" --log "/var/log/$app.log"

#=================================================
# START SERVICE
#=================================================
ynh_print_info "Start $app service..."

service shadowsocks start

sleep 10

#=================================================
# SEND A README FOR THE ADMIN
#=================================================

message=" $app server was successfully installed :)

Your Server IP: $ip
Your Server Port: $port
Your Password: $password
Your Encryption Method: $cipher
If you are facing any problem or want to improve this app, please open a new issue here: https://github.com/YunoHost-Apps/shadowsocks_ynh/issues "

ynh_send_readme_to_admin "$message" 

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Installation of $app completed"
