#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_print_info "Loading installation settings..."

app=$YNH_APP_INSTANCE_NAME
port=$(ynh_app_setting_get $app port)

#=================================================
# STANDARD REMOVE
#=================================================

if [ -f  /etc/init.d/shadowsocks ]; then
	/etc/init.d/shadowsocks stop
fi

#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_print_info "Removing dependencies"

# Remove metapackage and its dependencies
ynh_remove_app_dependencies

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE FROM ADMIN PANEL
#=================================================

# Remove a service from the admin panel, added by `yunohost service add`
if yunohost service status $app >/dev/null 2>&1
then
	ynh_print_info "Removing $app service"
	yunohost service remove "$app"
fi

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_print_info "Stopping and removing the systemd service"

# Remove the dedicated systemd config
ynh_remove_systemd_config


#=================================================
# CLOSE A PORT
#=================================================

if yunohost firewall list | grep -q "\- $port$"
then
	ynh_print_info "Closing port $port"
	ynh_exec_warn_less yunohost firewall disallow Both $port
fi

#=================================================
# SPECIFIC REMOVE
#=================================================
# REMOVE THE SHADOWSOCKS FILES
#=================================================
tmpdir="$(ynh_smart_mktemp 300)"

ynh_print_info "Extracting libsodium sorces into temp directory for installation..."
# Download, check integrity, uncompress and patch the source from libsodium.src
ynh_setup_source "${tmpdir}/${libsodium_file}" "libsodium"

# Remove Libsodium 
if [ -f /usr/lib/libsodium.a ]; then
       (
       cd ${tmpdir}/${libsodium_file}
       ./configure --prefix=/usr && make && make uninstall
       )
 
fi
 
sudo rm -Rf "$tmpdir"

# Remove a shadowsocks files
update-rc.d -f shadowsocks remove
ynh_secure_remove "/etc/shadowsocks.json"
ynh_secure_remove "/var/run/shadowsocks.pid"
ynh_secure_remove "/etc/init.d/shadowsocks"
ynh_secure_remove "/var/log/shadowsocks.log"
ynh_secure_remove "/etc/shadowsocks.json"

if [ -f /usr/local/shadowsocks_install.log ]; then
            cat /usr/local/shadowsocks_install.log | xargs rm -rf
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Removal of $app completed"
