#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

#Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

ynh_clean_setup () {
	#### Remove this function if there's nothing to clean before calling the remove script.
	true
}
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================
ynh_print_info "Loading settings..."

app=$YNH_APP_INSTANCE_NAME

port=$(ynh_app_setting_get $app port)

#=================================================
# STANDARD RESTORATION STEPS
#=================================================

# Open this port
ynh_exec_warn_less yunohost firewall allow --no-upnp Both $port

#=================================================
# SPECIFIC RESTORATION
#=================================================
# REINSTALL DEPENDENCIES
#=================================================
ynh_print_info "Reinstalling dependencies..."

# Define and install dependencies
ynh_install_app_dependencies $pkg_dependencies

# Restore conig file
ynh_restore_file /etc/shadowsocks.json

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_print_info "Setting up source files..."

### `ynh_setup_source` is used to install an app from a zip or tar.gz file,
### downloaded from an upstream source, like a git repository.
### `ynh_setup_source` use the file conf/app.src

tmpdir="$(ynh_smart_mktemp 300)"

ynh_print_info "Extracting libsodium sorces into temp directory for installation..."
# Download, check integrity, uncompress and patch the source from libsodium.src
ynh_setup_source "${tmpdir}/${libsodium_file}" "libsodium"

ynh_print_info "Extracting shadowsocks sorces into temp directory for installation..."
# Download, check integrity, uncompress and patch the source from shadowsocks.src
ynh_setup_source "${tmpdir}/shadowsocks" "shadowsocks"

#=================================================
# SPECIFIC SETUP
#=================================================

# Install Shadowsocks

    # Install libsodium
    if [ ! -f /usr/lib/libsodium.a ]; then
       (
       cd ${tmpdir}/${libsodium_file}
       ./configure --prefix=/usr && make && make install
       )
        
    fi

    # Install Shadowsocks
    (
    cd ${tmpdir}/shadowsocks
    python setup.py install --record /usr/local/shadowsocks_install.log
    )
    if [ -f /usr/bin/ssserver ] || [ -f /usr/local/bin/ssserver ]; then
        cp -f "../conf/shadowsocks" "/etc/init.d/."
        chmod +x /etc/init.d/shadowsocks
        update-rc.d -f shadowsocks defaults
    else
        ynh_die "Shadowsocks install failed! please open an issue here https://github.com/YunoHost-Apps/shadowsocks_ynh/issues"
fi

sudo rm -Rf "$tmpdir"

#=================================================
# ADVERTISE SERVICE IN ADMIN PANEL
#=================================================

yunohost service add $app --log "/var/log/$app.log"
yunohost service add $app --description $app daemon for Shadowsocks --log /var/log/$app.log

#=================================================
# RESTORE THE LOGROTATE CONFIGURATION
#=================================================

ynh_restore_file "/etc/logrotate.d/$app"

#=================================================
# GENERIC FINALIZATION
#=================================================

#=================================================
# START SERVICE
#=================================================
ynh_print_info "Start $app service..."

service shadowsocks start

sleep 10

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Restoration completed for $app"
